### 회원가입 요청
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "email": "testuser@example.com",
  "name": "테스트유저",
  "password": "password123"
}

### 로그인 요청
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}

### 유저 목록 가져오기 (AccessToken 필요)
GET http://localhost:8000/users
Authorization: Bearer yourAccessToken

### 내 정보 가져오기 (AccessToken 필요)
GET http://localhost:8000/users/me
Authorization: Bearer yourAccessToken

### 토큰 갱신 요청 (RefreshToken 필요)
POST http://localhost:8000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "yourRefreshToken"
}

### 유저 정보 수정하기 (유저 ID 필요)
PATCH http://localhost:8000/users/유저ID
Content-Type: application/json
Authorization: Bearer yourAccessToken

{
  "name": "수정된 이름",
  "isAdmin": true
}

### 유저 삭제하기 (유저 ID 필요)
DELETE http://localhost:8000/users/유저ID
Authorization: Bearer yourAccessToken

### 모든 포스트 가져오기
GET http://localhost:8000/posts

### 특정 포스트 가져오기 (타이틀 필요)
GET http://localhost:8000/posts/인공지능의-미래

### 포스트 생성하기
POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer yourAccessToken

{
  "title": "테스트 포스트 제목",
  "content": "이것은 테스트 포스트의 내용입니다.",
  "userId": "유저ID",
  "tags": ["tag1", "tag2"]
}

### 포스트 수정하기 (포스트 ID 필요)
PATCH http://localhost:8000/posts/포스트ID
Content-Type: application/json
Authorization: Bearer yourAccessToken

{
  "title": "수정된 포스트 제목"
}

### 포스트 삭제하기 (포스트 ID 필요)
DELETE http://localhost:8000/posts/포스트ID
Authorization: Bearer yourAccessToken

### 게시글 좋아요/취소 토글 (게시글 ID 필요)
POST http://localhost:8000/posts/포스트ID/like
Authorization: Bearer yourAccessToken

### 모든 댓글 가져오기
GET http://localhost:8000/comments

### 특정 포스트의 댓글 가져오기 (타이틀 필요)
GET http://localhost:8000/comments/인공지능의-미래

### 댓글 생성하기
POST http://localhost:8000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NTg1MTIwNC0yNDFjLTRlZWItODFkMS0wYTVmNjMzOGQwOTkiLCJpYXQiOjE3Mjg4ODgzMDIsImV4cCI6MTcyOTE0NzUwMn0.-T7l4MwOwFICMt57aWZPZo8lP8tCtBKydhAfMaiXf0E

{
  "content": "이것은 댓글입니다.",
  "userId": "75851204-241c-4eeb-81d1-0a5f6338d099",
  "postId": 1
}

### 대댓글 생성하기
POST http://localhost:8000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NTg1MTIwNC0yNDFjLTRlZWItODFkMS0wYTVmNjMzOGQwOTkiLCJpYXQiOjE3Mjg4ODgzMDIsImV4cCI6MTcyOTE0NzUwMn0.-T7l4MwOwFICMt57aWZPZo8lP8tCtBKydhAfMaiXf0E

{
  "content": "이것은 대댓글입니다.",
  "userId": "75851204-241c-4eeb-81d1-0a5f6338d099",
  "postId": 1,
  "parentCommentId": 20
}

### 댓글 수정하기 (댓글 ID 필요)
PATCH http://localhost:8000/comments/댓글ID
Content-Type: application/json
Authorization: Bearer yourAccessToken

{
  "content": "수정된 댓글 내용입니다."
}

### 댓글 삭제하기 (댓글 ID 필요)
DELETE http://localhost:8000/comments/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NTg1MTIwNC0yNDFjLTRlZWItODFkMS0wYTVmNjMzOGQwOTkiLCJpYXQiOjE3Mjg4ODgzMDIsImV4cCI6MTcyOTE0NzUwMn0.-T7l4MwOwFICMt57aWZPZo8lP8tCtBKydhAfMaiXf0E

### 댓글 좋아요/취소 토글 (댓글 ID 필요)
POST http://localhost:8000/comments/댓글ID/like
Authorization: Bearer yourAccessToken
